### ISSUE TITLE
Wie einstellen?

### ISSUE THREAD

**Issue by luebby** [NMarkgraf/FallstudienWebseite#4]
Hallo,

wie soll ich einstellen?
[Hier](https://github.com/luebby/Vorlesungen/issues/271) steht 

> Bitte stellt eure Fallstudien (als Rmd UND HTML UND PDF) in diesen Ordner ein: https://github.com/NMarkgraf/FallstudienWebseite/tree/master/case-studies

[Hier](https://github.com/NMarkgraf/FallstudienWebseite/blob/master/README.md) ins Unterverzeichnis `static`. 

(I.d.R. habe ich auch Daten und bib...)

Karsten

**Comment by NMarkgraf** [comment]
Erstes ist das Angebot von Sebastian (und mir) das noch anzupassen uns von Hand einzustellen. - Das mit den static wäre dann also ohne den Umweg über uns. ;-)

**Comment by luebby** [comment]
Erster Versuch unter b5a80be5f5c7de6a585bd2eca33089a26d2e5afe. Soweit ok?

**Comment by sebastiansauer** [comment]
👍

**Comment by luebby** [comment]
Wenn richtig, hier die nächste: a995515575efb264cca76d2cce02e56de819f272

Wie gesagt: habe noch ein paar...

**Comment by sebastiansauer** [comment]
Immer her damit, wenn du Zeit hast

**Comment by NMarkgraf** [comment]
GIB UNS MEHR! - Wir sind gierig! ;-)

**Comment by luebby** [comment]
Ein paar sind schon da, ein paar kommen noch...
Langsam die Platzhalter in `items.toml` löschen?

**Comment by NMarkgraf** [comment]
@luebby Aber sicher doch! - Sonst müssen wir viel zu schnell neue Hintergründe und Zahlen basteln. - Sebastian kommt ja so schon kaum interher. :-P
